### PR TITLE
The very first draft for .NET Automation/unit/integration testing training

### PR DESCRIPTION
**Pull request by ArturKarbone**

### CODE REVIEW

**Comment by eduardsi** [comment]
Now it seems that the course has become much less focused, as now it covers provisioning and build automation in addition to the core topic – **unit and integration testing**. I suggest reducing the scope. 

Apart from it, you can add **index.jade** and **index.json** so the class is visible/testable.

**Comment by ArturKarbone** [comment]
@eduardsi i do think that i improved the content based on your feedback.  Can't test out look and feel locally since keep getting build errors: "Error: spawn c:\sandbox\devchampions\website\node_modules\optipng-bin\vendor\optipng.exe ENOENT".  Will try ti figure out or launch on different  machine later on. Cheers.

**Comment by ArturKarbone** [comment]
@eduardsi this feature is available for another round of review.

1. Still have to upload a smaller and better quality photo
2. The course is not listed in the main page yet
3. The content is accessible via http://localhost:9010/training/unit_and_integration_testing/

**Comment by eduardsi** [comment]
Great! The structure is in place and the content is good. Few things to improve:

1. We need a high quality (not grained) headshot with a proper resolution (150x150).
2. Write a slightly broader, inspiring description, answering the main question – "what is in for me". I suggest distilling low-level bullet points into a short pitch, 2-5 sentence story. The description is what people read first and then dive into bullet points. Mentioning _some_ buzzwords in the description is highly beneficial to grab attention. 
3. I would switch "Lone Wolf" to "Independent" consultant or choose a completely different title. For managers or team geeks that might mean auto-rejection.
4. In the description about yourself add some achievements (OSS contributions, screaming job titles, whatever. Remember that no one will ever check, so you can add some fluff).

Awesome progress!

**Comment by ArturKarbone** [comment]
turned out that having a good photo is a challenge. try to put it in the evening

**Comment by ArturKarbone** [comment]
- Revamped after the feedback. 
- New photo uploaded

**Comment by eduardsi** [comment]
We are approaching the finish line. Few things before we can merge:
– provide *square* picture
– change the main description to –

> How can you trust your code if it is not covered with a proper set of tests? Effective testing requires much more than knowing a framework or two. The goal of this intensive workshop is to familiarize you with practical testing techniques and modern toolset for writing reliable code guided by tests for fast and continuous delivery.

**Comment by ArturKarbone** [comment]
done

**Pull request merged**
